name: Linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ${{ github.workspace }}/requirements/development.txt

      - name: Run flake8
        run: |
          python -m flake8 src
      
      - name: Run pylint
        run: |
          python -m pylint src
      
      - name: Run mypy
        run: |
          python -m mypy --install-types
          python -m mypy src